// Language rarity scores - higher = rarer = more points
// Based on number of countries that speak the language (fewer = rarer)
export const languageRarity: Record<string, number> = {
  // Very common (1-2 points)
  English: 1,
  French: 1,
  Spanish: 1,
  Arabic: 2,
  Portuguese: 2,

  // Common (3-4 points)
  German: 3,
  Chinese: 3,
  Russian: 3,
  Dutch: 4,
  Italian: 4,
  Swahili: 4,
  Malay: 4,

  // Moderate (5-7 points)
  Turkish: 5,
  Persian: 5,
  Korean: 6,
  Japanese: 7,
  Vietnamese: 7,
  Thai: 7,
  Greek: 6,
  Polish: 6,
  Romanian: 5,
  Hindi: 5,
  Bengali: 6,
  Urdu: 5,
  Tamil: 6,
  Swedish: 5,
  Norwegian: 5,
  Danish: 5,
  Finnish: 7,

  // Rare (8-10 points)
  Hungarian: 8,
  Czech: 8,
  Slovak: 8,
  Bulgarian: 8,
  Serbian: 7,
  Croatian: 7,
  Slovenian: 9,
  Albanian: 8,
  Macedonian: 9,
  Ukrainian: 7,
  Belarusian: 9,
  Lithuanian: 9,
  Latvian: 9,
  Estonian: 10,
  Georgian: 10,
  Armenian: 10,
  Azerbaijani: 8,
  Kazakh: 9,
  Uzbek: 8,
  Turkmen: 10,
  Tajik: 9,
  Kyrgyz: 10,
  Mongolian: 10,
  Nepali: 9,
  Sinhala: 10,
  Burmese: 10,
  Khmer: 10,
  Lao: 10,
  Indonesian: 6,
  Filipino: 8,
  Hebrew: 9,
  Amharic: 9,
  Somali: 8,
  Hausa: 7,
  Yoruba: 8,
  Igbo: 9,
  Zulu: 8,
  Afrikaans: 7,
  Catalan: 9,
  Basque: 10,
  Welsh: 10,
  Irish: 9,
  Icelandic: 10,
  Maltese: 10,
  Luxembourgish: 10,
}

// Countries with their official/widely spoken languages
export const countryLanguages: Record<string, string[]> = {
  // Europe
  "United Kingdom": ["English", "Welsh", "Irish"],
  Ireland: ["English", "Irish"],
  France: ["French"],
  Germany: ["German"],
  Austria: ["German"],
  Switzerland: ["German", "French", "Italian"],
  Belgium: ["Dutch", "French", "German"],
  Netherlands: ["Dutch"],
  Luxembourg: ["Luxembourgish", "French", "German"],
  Spain: ["Spanish", "Catalan", "Basque"],
  Portugal: ["Portuguese"],
  Italy: ["Italian"],
  Greece: ["Greek"],
  Malta: ["Maltese", "English"],
  Cyprus: ["Greek", "Turkish", "English"],
  Poland: ["Polish"],
  "Czech Republic": ["Czech"],
  Slovakia: ["Slovak"],
  Hungary: ["Hungarian"],
  Romania: ["Romanian"],
  Bulgaria: ["Bulgarian"],
  Serbia: ["Serbian"],
  Croatia: ["Croatian"],
  Slovenia: ["Slovenian"],
  "Bosnia and Herzegovina": ["Serbian", "Croatian"],
  Montenegro: ["Serbian"],
  "North Macedonia": ["Macedonian", "Albanian"],
  Albania: ["Albanian"],
  Kosovo: ["Albanian", "Serbian"],
  Ukraine: ["Ukrainian", "Russian"],
  Belarus: ["Belarusian", "Russian"],
  Moldova: ["Romanian", "Russian"],
  Lithuania: ["Lithuanian"],
  Latvia: ["Latvian", "Russian"],
  Estonia: ["Estonian", "Russian"],
  Finland: ["Finnish", "Swedish"],
  Sweden: ["Swedish"],
  Norway: ["Norwegian"],
  Denmark: ["Danish"],
  Iceland: ["Icelandic"],
  Russia: ["Russian"],

  // Middle East & Central Asia
  Turkey: ["Turkish"],
  Georgia: ["Georgian"],
  Armenia: ["Armenian"],
  Azerbaijan: ["Azerbaijani", "Russian"],
  Kazakhstan: ["Kazakh", "Russian"],
  Uzbekistan: ["Uzbek", "Russian"],
  Turkmenistan: ["Turkmen", "Russian"],
  Tajikistan: ["Tajik", "Russian"],
  Kyrgyzstan: ["Kyrgyz", "Russian"],
  Iran: ["Persian"],
  Iraq: ["Arabic", "Kurdish"],
  Syria: ["Arabic"],
  Lebanon: ["Arabic", "French"],
  Jordan: ["Arabic"],
  Israel: ["Hebrew", "Arabic"],
  Palestine: ["Arabic"],
  "Saudi Arabia": ["Arabic"],
  Yemen: ["Arabic"],
  Oman: ["Arabic"],
  "United Arab Emirates": ["Arabic", "English"],
  Qatar: ["Arabic", "English"],
  Bahrain: ["Arabic"],
  Kuwait: ["Arabic"],
  Afghanistan: ["Persian", "Uzbek"],

  // South Asia
  India: ["Hindi", "English", "Bengali", "Tamil", "Urdu"],
  Pakistan: ["Urdu", "English"],
  Bangladesh: ["Bengali"],
  Nepal: ["Nepali"],
  "Sri Lanka": ["Sinhala", "Tamil", "English"],
  Bhutan: ["Nepali"],
  Maldives: ["English"],

  // Southeast Asia
  Thailand: ["Thai"],
  Vietnam: ["Vietnamese"],
  Myanmar: ["Burmese"],
  Cambodia: ["Khmer"],
  Laos: ["Lao"],
  Malaysia: ["Malay", "English", "Chinese", "Tamil"],
  Singapore: ["English", "Malay", "Chinese", "Tamil"],
  Indonesia: ["Indonesian", "Malay"],
  Philippines: ["Filipino", "English"],
  Brunei: ["Malay", "English"],
  "Timor-Leste": ["Portuguese"],

  // East Asia
  China: ["Chinese"],
  Japan: ["Japanese"],
  "South Korea": ["Korean"],
  "North Korea": ["Korean"],
  Mongolia: ["Mongolian", "Russian"],
  Taiwan: ["Chinese"],

  // Africa
  Egypt: ["Arabic"],
  Libya: ["Arabic"],
  Tunisia: ["Arabic", "French"],
  Algeria: ["Arabic", "French"],
  Morocco: ["Arabic", "French"],
  Sudan: ["Arabic", "English"],
  "South Sudan": ["English", "Arabic"],
  Ethiopia: ["Amharic", "English"],
  Eritrea: ["Arabic"],
  Somalia: ["Somali", "Arabic"],
  Djibouti: ["French", "Arabic", "Somali"],
  Kenya: ["Swahili", "English"],
  Uganda: ["English", "Swahili"],
  Tanzania: ["Swahili", "English"],
  Rwanda: ["French", "English", "Swahili"],
  Burundi: ["French", "Swahili"],
  "Democratic Republic of the Congo": ["French", "Swahili"],
  "Republic of the Congo": ["French"],
  Gabon: ["French"],
  Cameroon: ["French", "English"],
  "Central African Republic": ["French"],
  Chad: ["French", "Arabic"],
  Niger: ["French", "Hausa"],
  Nigeria: ["English", "Hausa", "Yoruba", "Igbo"],
  Benin: ["French"],
  Togo: ["French"],
  Ghana: ["English"],
  "Ivory Coast": ["French"],
  Liberia: ["English"],
  "Sierra Leone": ["English"],
  Guinea: ["French"],
  "Guinea-Bissau": ["Portuguese"],
  Senegal: ["French"],
  Gambia: ["English"],
  Mali: ["French"],
  "Burkina Faso": ["French"],
  Mauritania: ["Arabic", "French"],
  "Western Sahara": ["Arabic", "Spanish"],
  "South Africa": ["English", "Afrikaans", "Zulu"],
  Namibia: ["English", "Afrikaans", "German"],
  Botswana: ["English"],
  Zimbabwe: ["English"],
  Zambia: ["English"],
  Malawi: ["English"],
  Mozambique: ["Portuguese"],
  Madagascar: ["French"],
  Mauritius: ["English", "French"],
  Seychelles: ["English", "French"],
  Comoros: ["French", "Arabic"],
  Angola: ["Portuguese"],
  Lesotho: ["English"],
  Eswatini: ["English"],

  // North America
  "United States": ["English", "Spanish"],
  Canada: ["English", "French"],
  Mexico: ["Spanish"],

  // Central America & Caribbean
  Guatemala: ["Spanish"],
  Belize: ["English", "Spanish"],
  Honduras: ["Spanish"],
  "El Salvador": ["Spanish"],
  Nicaragua: ["Spanish"],
  "Costa Rica": ["Spanish"],
  Panama: ["Spanish"],
  Cuba: ["Spanish"],
  Jamaica: ["English"],
  Haiti: ["French"],
  "Dominican Republic": ["Spanish"],
  "Puerto Rico": ["Spanish", "English"],
  "Trinidad and Tobago": ["English"],
  Bahamas: ["English"],
  Barbados: ["English"],
  Guyana: ["English"],
  Suriname: ["Dutch"],

  // South America
  Colombia: ["Spanish"],
  Venezuela: ["Spanish"],
  Ecuador: ["Spanish"],
  Peru: ["Spanish"],
  Bolivia: ["Spanish"],
  Chile: ["Spanish"],
  Argentina: ["Spanish"],
  Uruguay: ["Spanish"],
  Paraguay: ["Spanish"],
  Brazil: ["Portuguese"],

  // Oceania
  Australia: ["English"],
  "New Zealand": ["English"],
  "Papua New Guinea": ["English"],
  Fiji: ["English"],
  Vanuatu: ["English", "French"],
  Samoa: ["English"],
  Tonga: ["English"],
}

// Get all unique countries
export const allCountries = Object.keys(countryLanguages)

// Get all unique languages
export const allLanguages = [...new Set(Object.values(countryLanguages).flat())]

// Helper to get countries that speak a language
export function getCountriesByLanguage(language: string): string[] {
  return allCountries.filter((country) =>
    countryLanguages[country].includes(language)
  )
}

// Helper to get rarity score for a language (default to 5 if not found)
export function getLanguageRarity(language: string): number {
  return languageRarity[language] ?? 5
}
