export const languageRarity: Record<string, number> = {
  "Abkhaz": 5,
  "Afar": 5,
  "Afrikaans": 4,
  "Albanian": 2,
  "Alsatian": 5,
  "Amerindian Languages": 4,
  "Amharic": 5,
  "Arabic": 1,
  "Armenian": 3,
  "Assamese": 5,
  "Assyrian Neo Aramaic": 5,
  "Ateso": 5,
  "Aymara": 4,
  "Azari": 5,
  "Azerbaijani": 4,
  "Bahasa Indonesian": 4,
  "Balochi": 5,
  "Bambara": 5,
  "Bandjabi Gambia": 5,
  "Bangla": 5,
  "Bantawa": 5,
  "Bantu": 4,
  "Baoulé": 5,
  "Bapounou/eschira": 5,
  "Basque": 4,
  "Bateke": 5,
  "Belorussian": 5,
  "Bemba": 5,
  "Bengali": 5,
  "Berber": 4,
  "Bhojpuri": 4,
  "Bislama": 5,
  "Bosnian": 3,
  "Brahui": 5,
  "Breton": 5,
  "Brong Ahafo": 5,
  "Bubi": 5,
  "Bulgarian": 5,
  "Burmese": 5,
  "Burushaski": 5,
  "Cakchiquel": 5,
  "Cantonese": 2,
  "Castilian": 5,
  "Catalan": 4,
  "Catalán": 5,
  "Cebuano": 5,
  "Chewa": 5,
  "Chibarwe": 5,
  "Chichewa": 5,
  "Chin": 5,
  "Chinese": 5,
  "Chukese": 5,
  "Corsican": 5,
  "Cotocoli": 5,
  "Creole": 1,
  "Crioulo": 5,
  "Criuolo": 5,
  "Croatian": 2,
  "Czech": 4,
  "Dagbani": 5,
  "Danish": 5,
  "Dari": 5,
  "Dhivehi": 5,
  "Diaula": 5,
  "Dinka": 4,
  "Dutch": 2,
  "Dzala": 5,
  "Dzongkha": 5,
  "English": 1,
  "Estonian": 5,
  "Ewe": 4,
  "Fang": 4,
  "Fanti": 5,
  "Faroese": 5,
  "Farsi": 3,
  "Fiji Hindi": 5,
  "Fijian": 5,
  "Filipino": 5,
  "Finnish": 4,
  "Flemish": 5,
  "Fon": 5,
  "French": 1,
  "French Patois": 5,
  "Frisian": 5,
  "Fula": 5,
  "Fulfulde": 3,
  "Ga": 5,
  "Gagauz": 5,
  "Galician": 5,
  "Galole": 5,
  "Garifuna": 4,
  "Georgian": 5,
  "German": 1,
  "Greek": 3,
  "Greenlandic": 5,
  "Guaragigna": 5,
  "Guaraní": 5,
  "Gujarati": 5,
  "Hakka": 2,
  "Hansa": 5,
  "Hausa": 4,
  "Hazaragi": 5,
  "Hebrew": 4,
  "Hindi": 2,
  "Hindko": 5,
  "Hiri Motu": 5,
  "Hungarian": 2,
  "I-kiribati": 5,
  "Igbo": 4,
  "Icelandic": 5,
  "Ilocano": 5,
  "Irish": 4,
  "Italian": 1,
  "Japanese": 5,
  "Javanese": 5,
  "Jola-fonyi": 5,
  "Kabyé": 5,
  "Kalanga": 5,
  "Kamtok": 5,
  "Kannada": 5,
  "Kaonde": 5,
  "Karen": 5,
  "Kashmiri": 5,
  "Kazak": 5,
  "Kekchi": 5,
  "Kemak": 5,
  "Kheng": 5,
  "Khmer": 4,
  "Kikongo": 4,
  "Kingwana": 5,
  "Kinyarwanda": 5,
  "Kirundi": 5,
  "Koisan": 5,
  "Korean": 4,
  "Kosraean": 5,
  "Krio": 5,
  "Kunama": 5,
  "Kurdish": 2,
  "Kyrgyz": 5,
  "Lao": 3,
  "Latvian": 5,
  "Lingala": 4,
  "Lithuanian": 4,
  "Lozi": 5,
  "Luganda": 5,
  "Lunda": 5,
  "Luo": 5,
  "Luvale": 5,
  "Luxermbourgish": 5,
  "Macedonian": 5,
  "Madinka": 5,
  "Maithali": 5,
  "Malagasy": 5,
  "Malay": 3,
  "Malayalam": 5,
  "Malinké": 5,
  "Maltese": 5,
  "Mam": 5,
  "Mambae": 5,
  "Mandarin": 2,
  "Mandingo": 5,
  "Mandinka": 5,
  "Mandjaque": 5,
  "Maninkakan": 5,
  "Maori": 5,
  "Marathi": 5,
  "Marshallese": 5,
  "Mayan": 5,
  "Mende": 5,
  "Mina": 5,
  "Minnan": 2,
  "Moldovan": 5,
  "Monégasque": 5,
  "Mongolian": 4,
  "Monokutuba": 5,
  "Montenegrin": 5,
  "Myene": 5,
  "Nambya": 5,
  "Nauruan": 5,
  "Ndau": 5,
  "Ndebele": 4,
  "Nepali": 4,
  "Newar": 5,
  "Norwegian": 5,
  "Nuer": 5,
  "Nyanja": 5,
  "Oriya": 5,
  "Orominga": 5,
  "Palau": 5,
  "Papiamento": 4,
  "Pashtu": 4,
  "Pidgin English": 5,
  "Pohnpeian": 5,
  "Polish": 3,
  "Portuguese": 1,
  "Pulaar": 4,
  "Punjabi": 4,
  "Quechua": 4,
  "Quéchua": 5,
  "Quiche": 5,
  "Rohingya": 5,
  "Romanian": 4,
  "Romansch": 5,
  "Russian": 1,
  "Sami": 3,
  "Samoan": 5,
  "Sangho": 5,
  "Sanskrit": 5,
  "Sara": 5,
  "Sarahole": 5,
  "Scots": 5,
  "Secondary Ethnic Languages": 5,
  "Serbian": 2,
  "Serbo-croatian": 5,
  "Serer": 5,
  "Serer-sine": 5,
  "Seselwa": 5,
  "Sesotho": 4,
  "Sesotho Sa Leboa": 5,
  "Setswana": 4,
  "Shangani": 5,
  "Shikomoro": 5,
  "Shona": 5,
  "Sign Language": 5,
  "Sindhi": 4,
  "Sinhala": 5,
  "Siraiki": 5,
  "Slovak": 4,
  "Slovene": 4,
  "Slovenian": 5,
  "Solomon Pidjin": 5,
  "Somali": 3,
  "Songhai": 5,
  "Sotho": 5,
  "Spanish": 1,
  "Surinamese": 5,
  "Susu": 5,
  "Swahili": 2,
  "Swati": 5,
  "Swazi": 5,
  "Swedish": 4,
  "Tagalog": 5,
  "Tajik": 4,
  "Tamang": 5,
  "Tamil": 2,
  "Telugu": 5,
  "Temne": 5,
  "Tetum": 5,
  "Thai": 5,
  "Tharu": 5,
  "Tibetan": 5,
  "Tigre": 5,
  "Tigrigna": 5,
  "Tigrinya": 5,
  "Tok Pisin": 5,
  "Tonga": 4,
  "Tongan": 5,
  "Tosk": 5,
  "Tshangla": 5,
  "Tshiluba": 5,
  "Tshivenda": 5,
  "Tswana": 5,
  "Turkic": 5,
  "Turkish": 2,
  "Turkmen": 5,
  "Tuvaluan": 5,
  "Twi": 5,
  "Ukrainian": 4,
  "Urdu": 2,
  "Uyghur": 5,
  "Uygur": 5,
  "Uzbek": 3,
  "Venda": 5,
  "Vietnamese": 5,
  "Welsh": 5,
  "Wolof": 2,
  "Wu": 5,
  "Xhosa": 3,
  "Xinca": 5,
  "Xitsonga": 5,
  "Yapase": 5,
  "Yoruba": 4,
  "Zande": 5,
  "Zhuang": 5,
  "Zulu": 4,
}

export const countryLanguages: Record<string, string[]> = {
  "Afghanistan": ["Dari", "Farsi", "Hazaragi", "Pashtu"],
  "Albania": ["Albanian", "Tosk", "Greek"],
  "Algeria": ["Arabic", "Berber", "French"],
  "Andorra": ["Castilian", "Catalán", "French", "Portuguese"],
  "Angola": ["Bantu", "Portuguese"],
  "Antigua and Barbuda": ["English"],
  "Argentina": ["English", "French", "German", "Italian", "Spanish"],
  "Armenia": ["Armenian", "Russian"],
  "Aruba": ["Papiamento", "Dutch", "English", "Spanish"],
  "Australia": ["English"],
  "Austria": ["Croatian", "German", "Hungarian", "Slovene"],
  "Azerbaijan": ["Armenian", "Azerbaijani", "Russian"],
  "Bahamas": ["Creole", "English"],
  "Bahrain": ["Arabic", "English", "Farsi", "Urdu"],
  "Bangladesh": ["Bangla", "English"],
  "Barbados": ["English"],
  "Belarus": ["Belorussian", "Russian"],
  "Belize": ["Creole", "English", "Garifuna", "Mayan", "Spanish"],
  "Belgium": ["Dutch", "French", "German"],
  "Benin": ["Fon", "French", "Yoruba"],
  "Bhutan": ["Dzongkha", "Tshangla", "Nepali", "Dzala", "Kheng", "Bantawa"],
  "Bolivia": ["Aymara", "Quechua", "Spanish"],
  "Bosnia and Herzegovina": ["Bosnian", "Croatian", "Serbian"],
  "Botswana": ["English", "Setswana"],
  "Brazil": ["English", "French", "Portuguese", "Spanish"],
  "Brunei": ["Mandarin", "English", "Malay", "Minnan", "Cantonese", "Hakka"],
  "Bulgaria": ["Bulgarian", "Secondary Ethnic Languages"],
  "Burkina Faso": ["French"],
  "Burundi": ["French", "Kirundi", "Swahili"],
  "Cambodia": ["English", "French", "Khmer", "Lao"],
  "Cameroon": ["Fulfulde", "English", "French", "Kamtok"],
  "Canada": ["English", "French"],
  "Cape Verde": ["Criuolo", "Portuguese"],
  "Central African Republic": ["Arabic", "French", "Hansa", "Sangho", "Swahili"],
  "Chad": ["Arabic", "French", "Sara"],
  "Chile": ["Spanish"],
  "China": ["Mongolian", "Cantonese", "Tibetan", "Minnan", "Hakka", "Uygur", "Wu", "Uyghur", "Zhuang", "Mandarin"],
  "Colombia": ["Spanish"],
  "Comoros": ["Arabic", "French", "Shikomoro"],
  "Republic of Congo": ["French", "Kikongo", "Lingala", "Monokutuba"],
  "Democratic Republic of Congo": ["French", "Kikongo", "Kingwana", "Lingala", "Tshiluba"],
  "Costa Rica": ["English", "Spanish"],
  "Cote d'Ivoire": ["Diaula", "Baoulé", "French"],
  "Croatia": ["Bosnian", "Croatian", "Czech", "German", "Hungarian", "Italian", "Serbian", "Slovak"],
  "Cuba": ["Spanish"],
  "Curacao": ["Papiamento", "Dutch", "English"],
  "Cyprus": ["English", "Greek", "Turkish"],
  "Czech Republic": ["Czech"],
  "Denmark": ["Danish", "English", "Faroese", "German", "Greenlandic"],
  "Djibouti": ["English", "Arabic", "French", "French Patois", "Somali"],
  "Dominican Republic": ["Spanish"],
  "East Timor": ["Kemak", "Bahasa Indonesian", "English", "Galole", "Mambae", "Portuguese", "Tetum"],
  "Ecuador": ["Quechua", "Spanish"],
  "Egypt": ["Arabic", "English", "French"],
  "El Salvador": ["Spanish"],
  "Equatorial Guinea": ["Bubi", "Fang", "French", "Igbo", "Pidgin English", "Spanish"],
  "Eritrea": ["Afar", "Arabic", "Tigre", "Kunama", "Tigrinya"],
  "Estonia": ["Estonian", "Finnish", "Russian", "Ukrainian"],
  "Ethiopia": ["Amharic", "Arabic", "English", "Guaragigna", "Orominga", "Somali", "Tigrigna"],
  "Fiji": ["English", "Fijian", "Fiji Hindi"],
  "Finland": ["Finnish", "Russian", "Sami", "Swedish"],
  "France": ["Alsatian", "Basque", "Breton", "Catalan", "Corsican", "Flemish", "French"],
  "Gambia": ["Madinka", "Pulaar", "Wolof", "English"],
  "Gabon": ["Bandjabi Gambia", "Bapounou/eschira", "Bateke", "Creole", "Fang", "French", "Fula", "Jola-fonyi", "Mandingo", "Mandinka", "Mandjaque", "Maninkakan", "Myene", "Pulaar", "Sarahole", "Serer-sine", "English", "Wolof"],
  "Georgia": ["Abkhaz", "Armenian", "Azerbaijani", "Georgian", "Russian"],
  "Germany": ["German"],
  "Ghana": ["Dagbani", "English", "Ewe", "Fanti", "Ga", "Brong Ahafo", "Twi"],
  "Greece": ["English", "Greek"],
  "Grenada": ["English", "French"],
  "Guatemala": ["Cakchiquel", "Garifuna", "Quiche", "Kekchi", "Mam", "Xinca", "Spanish"],
  "Guinea": ["French", "Fulfulde", "Malinké", "Susu"],
  "Guinea-Bissau": ["Crioulo", "Portuguese"],
  "Guyana": ["Amerindian Languages", "Creole", "English", "Hindi", "Urdu"],
  "Haiti": ["Creole", "French"],
  "Honduras": ["Amerindian Languages", "English", "Spanish"],
  "Hong Kong": ["Cantonese", "Mandarin"],
  "Hungary": ["Hungarian"],
  "Iceland": ["English", "German", "Icelandic"],
  "India": ["Assamese", "Bengali", "English", "Gujarati", "Hindi", "Kannada", "Kashmiri", "Malayalam", "Marathi", "Oriya", "Punjabi", "Sanskrit", "Sindhi", "Tamil", "Telugu", "Urdu"],
  "Indonesia": ["Bahasa Indonesian", "Dutch", "English", "Javanese"],
  "Iran": ["Arabic", "Azari", "Farsi", "Kurdish"],
  "Iraq": ["Arabic", "Assyrian Neo Aramaic", "Kurdish"],
  "Ireland": ["English", "Irish"],
  "Israel": ["Arabic", "English", "Hebrew", "Russian"],
  "Italy": ["French", "German", "Italian", "Slovene"],
  "Jamaica": ["English", "Creole"],
  "Japan": ["Japanese"],
  "Jordan": ["Arabic", "English"],
  "Kazakhstan": ["Kazak", "Russian"],
  "Kenya": ["English", "Swahili"],
  "Kiribati": ["English", "I-kiribati"],
  "Kuwait": ["Arabic", "English"],
  "North Korea": ["Korean"],
  "South Korea": ["Korean"],
  "Kyrgyzstan": ["Kyrgyz", "Russian"],
  "Laos": ["English", "French", "Lao"],
  "Latvia": ["Latvian", "Russian"],
  "Lebanon": ["Arabic", "English", "French"],
  "Lesotho": ["English", "Sesotho", "Xhosa", "Zulu"],
  "Liberia": ["English"],
  "Libya": ["Arabic", "English", "Italian"],
  "Liechtenstein": ["Lithuanian", "German", "Polish", "Russian"],
  "Lithuania": ["Lithuanian", "Russian", "Polish"],
  "Luxembourg": ["French", "German", "Luxermbourgish"],
  "North Macedonia": ["Albanian", "Macedonian", "Turkish"],
  "Madagascar": ["French", "Malagasy"],
  "Malawi": ["Chichewa", "English"],
  "Malaysia": ["Cantonese", "Mandarin", "English", "Malay", "Tamil"],
  "Maldives": ["Arabic", "Dhivehi", "English", "Hindi"],
  "Mali": ["Bambara", "Fulfulde", "French"],
  "Malta": ["English", "Maltese"],
  "Marshall Islands": ["English", "Marshallese"],
  "Mauritania": ["Arabic", "French", "Wolof"],
  "Mauritius": ["Bhojpuri", "Creole", "English", "French", "Hakka", "Hindi", "Urdu"],
  "Mexico": ["Spanish"],
  "Micronesia": ["Chukese", "English", "Kosraean", "Pohnpeian", "Yapase"],
  "Moldova": ["Gagauz", "Moldovan", "Romanian", "Russian", "Turkish"],
  "Monaco": ["English", "French", "Italian", "Monégasque"],
  "Mongolia": ["Chinese", "Mongolian", "Russian", "Turkic"],
  "Montenegro": ["Montenegrin", "Serbian", "Bosnian", "Albanian", "Croatian"],
  "Morocco": ["Arabic", "Berber", "French", "Spanish"],
  "Mozambique": ["Bantu", "Portuguese"],
  "Myanmar": ["Chin", "Karen", "Rohingya", "Burmese"],
  "Namibia": ["Afrikaans", "English", "German"],
  "Nauru": ["English", "Nauruan"],
  "Nepal": ["Bhojpuri", "Maithali", "Nepali", "Newar", "Tamang", "Tharu"],
  "The Netherlands": ["Dutch", "Frisian"],
  "New Zealand": ["English", "Maori"],
  "Nicaragua": ["Spanish"],
  "Niger": ["Arabic", "French", "Hausa", "Songhai"],
  "Nigeria": ["English", "Hausa", "Igbo", "Yoruba"],
  "Norway": ["Sami", "Norwegian"],
  "Oman": ["Arabic", "English"],
  "Pakistan": ["Balochi", "Brahui", "Burushaski", "English", "Hindko", "Pashtu", "Punjabi", "Sindhi", "Siraiki", "Urdu"],
  "Palau": ["Palau"],
  "Palestine": ["Arabic", "English", "French", "Hebrew"],
  "Papua New Guinea": ["English", "Hiri Motu", "Tok Pisin"],
  "Panama": ["Spanish"],
  "Paraguay": ["Guaraní", "Spanish"],
  "Peru": ["Aymara", "Quéchua", "Spanish"],
  "The Philippines": ["Cebuano", "English", "Filipino", "Ilocano", "Tagalog"],
  "Poland": ["Polish"],
  "Portugal": ["Portuguese"],
  "Qatar": ["Arabic", "English"],
  "Romania": ["German", "Hungarian", "Romanian"],
  "Russia": ["Russian"],
  "Rwanda": ["English", "French", "Kinyarwanda"],
  "St. Kitts and Nevis": ["English"],
  "St. Lucia": ["English", "Creole"],
  "St. Vincent and the Grenadines": ["English", "Creole"],
  "Samoa": ["English", "Samoan"],
  "San Marino": ["Italian"],
  "Sao Tome and Príncipe": ["Portuguese"],
  "Saudi Arabia": ["Arabic", "English"],
  "Senegal": ["French", "Serer", "Wolof"],
  "Serbia": ["Albanian", "Serbian"],
  "Seychelles": ["English", "French", "Seselwa"],
  "Sierra Leone": ["English", "Krio", "Mende", "Temne"],
  "Singapore": ["Mandarin", "Cantonese", "English", "Malay", "Tamil"],
  "Slovakia": ["Hungarian", "Slovak"],
  "Slovenia": ["Serbo-croatian", "Slovenian"],
  "Solomon Islands": ["English", "Solomon Pidjin"],
  "Somalia": ["Arabic", "English", "Italian", "Somali"],
  "South Africa": ["Afrikaans", "English", "Ndebele", "Sesotho", "Sesotho Sa Leboa", "Setswana", "Swati", "Tshivenda", "Xhosa", "Xitsonga", "Zulu"],
  "South Sudan": ["Arabic", "Dinka", "English", "Nuer", "Zande"],
  "Spain": ["Basque", "Spanish", "Catalan", "English", "Galician"],
  "Sri Lanka": ["Sinhala", "Tamil", "English"],
  "Sudan": ["Arabic", "Dinka", "English"],
  "Suriname": ["Dutch", "English", "Surinamese"],
  "Swaziland": ["English", "Swazi"],
  "Sweden": ["Swedish", "Sami"],
  "Switzerland": ["French", "German", "Italian", "Romansch"],
  "Syria": ["Arabic", "French", "English", "Kurdish"],
  "Taiwan": ["Mandarin", "Minnan", "Hakka"],
  "Tajikistan": ["Russian", "Tajik", "Uzbek"],
  "Tanzania": ["English", "Swahili"],
  "Thailand": ["Mandarin", "Minnan", "English", "Thai", "Lao"],
  "Togo": ["Cotocoli", "Ewe", "French", "Kabyé", "Mina"],
  "Tonga": ["English", "Tongan"],
  "Trinidad and Tobago": ["English", "French", "Hindi", "Spanish"],
  "Tunisia": ["Arabic", "French"],
  "Turkey": ["Turkish", "Kurdish"],
  "Turkmenistan": ["Russian", "Turkmen", "Uzbek"],
  "Tuvalu": ["English", "Tuvaluan"],
  "Uganda": ["Ateso", "English", "Luganda", "Luo", "Swahili"],
  "Ukraine": ["Ukrainian"],
  "United Arab Emirates": ["Arabic", "English"],
  "United Kingdom": ["English", "Scots", "Welsh", "Irish"],
  "United States": ["English", "Spanish"],
  "Uruguay": ["Spanish"],
  "Uzbekistan": ["Russian", "Tajik", "Uzbek"],
  "Vanuatu": ["Bislama", "English", "French"],
  "Vatican City": ["Italian"],
  "Venezuela": ["Spanish"],
  "Vietnam": ["Cantonese", "English", "French", "Khmer", "Vietnamese"],
  "Yemen": ["Arabic"],
  "Zambia": ["English", "Bemba", "Nyanja", "Lozi", "Tonga", "Luvale", "Lunda", "Kaonde"],
  "Zimbabwe": ["Chewa", "Chibarwe", "English", "Kalanga", "Koisan", "Nambya", "Ndau", "Ndebele", "Shangani", "Shona", "Sign Language", "Sotho", "Tonga", "Tswana", "Venda", "Xhosa"],
}

export const allCountries = Object.keys(countryLanguages)

export const allLanguages = [...new Set(Object.values(countryLanguages).flat())]

export function getCountriesByLanguage(language: string): string[] {
  return allCountries.filter((country) =>
    countryLanguages[country].includes(language)
  )
}

export function getLanguageRarity(language: string): number {
  return languageRarity[language] ?? 1
}
